### ISSUE TITLE
1.0 release built against the wrong redist

### ISSUE THREAD

**Issue by TingPing** [rahatarmanahmed/hcspotify#3]
Users downloading it will get an error if they do not have the [2015 redist](https://www.microsoft.com/en-us/download/details.aspx?id=48145) installed as HexChat itself only requires 2013.

**Comment by rahatarmanahmed** [comment]
Rebuilt with VS2013 and replaced the [1.0 release files](https://github.com/rahatarmanahmed/hcspotify/releases/tag/1.0).
